### PR TITLE
#486 - Refactoring project structure (3.3.0) 

### PR DESCRIPTION
**Pull request by astier**
- Replace explicit array type with <>
- Collapse redundant catch blocks
- Inline redundant variable
- Correct misspelling
- Remove unnecessary import
- Make use of Comparator.comparing()
- Remove unnecessary String.format()

### CODE REVIEW

**Comment by reckart** [comment]
Commit messages don't match convention.

**Comment by reckart** [comment]
Why do you link these commits to issue #384 *Whole project export does not include in progress curation* ?!

**Comment by reckart** [comment]
Commit messages should refer issue #486 - Refactoring project structure (3.3.0) like

```
#486 - Refactoring project structure (3.3.0) 
- Java 7 features
- Replace explicit array type with <>
- Collapse redundant catch blocks
```

**Comment by astier** [comment]
Commit message fixed.

**Pull request merged**
