### PR TITLE
Reset/Recreate default admin account

### PR DESCRIPTION
**Pull request by lokeshmekala**
Reset/ Recreate the default admin account.
The current version of webanno software creates a default admin account when there are no users account found. When the software runs for the first time, there will not be any user accounts, Hence to allow the user to access the software, webanno creates a default admin account with the username as admin and password as admin. We have to provide the liberty to the user to create his default admin account. 
To allow the user to create his default admin account, we provide two environment variables. One of the environment variables contains the default username and the other default password(WEBANNO_ENV_ADMIN_NAME, WEBANNO_ENV_ADMIN_PASS). If these variables are present, then these values are considered to create the default admin account. If the values are not present, the default admin account is created with username as "admin" and password as "admin".

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
The title of the PR is "Reset/Recreate default admin account". However, setting the variables does not in any way reset or recreate the admin account. They only change the username and password of the default admin account that is created when no user exists in the database. 

So it looks to me like the PR does not meet the goal of resetting/recreating the default admin account.

There is an issue about resetting/re-creating the default admin account, but it describes a different approach: https://github.com/webanno/webanno/issues/70

Mind that development on WebAnno has largely ceased and efforts have been focussing on [INCEpTION](https://inception-project.github.io) instead. Most WebAnno projects can be simply exported from WebAnno and then imported into INCEpTION.

The issue of resetting/recreating the default admin account has also been addressed already in INCEpTION: https://github.com/inception-project/inception/issues/2503

Also, INCEpTION has a way of setting a default admin PW for unsupervised deployments: https://github.com/inception-project/inception/issues/2164

**Comment by reckart** [comment]
@munterkalmsteiner ?

**Comment by munterkalmsteiner** [comment]
@reckart Please ignore and close. Students of mine have used the wrong repository for the pull request. I am very sorry for the noise.

**Pull request closed without merging**
