### PR TITLE
#1598 ApplicationEvent when annopage is created

### PR DESCRIPTION
**Pull request by UWinch**
**What's in the PR**
* Event will be published when annotation page is created.

**How to test manually**
* Annotate a bit and switch between pages to test that loading/creating the annopage is still working.

### CODE REVIEW

**Comment by UWinch** [comment]
Can be reviewed and merged

**Comment by UWinch** [comment]
I have an annotationeditorextension that should only render some suggestions after the corresponding sidebar has been opened but not directly when the annotationpage is opened from either the dashboard or an url. This means we must somehow find out when the user leaves the page or how I want to do it here, when the user freshly opens the annotation page.
We thought about saving a state as metadata to the page, this would tell other UI elements if the suggestions should be shown but not the annotationeditorextension, because it has no knowledge of the annotation page and its metadata.

**Comment by reckart** [comment]
I assume this is about rendering curation stuff on the annotation page only if the curation sidebar is open. I believe we were discussing to consider curation "active" not based on whether the sidebar is open but rather have some "start/stop curation" button in the sidebar - similar to active learning in INCEpTION. So then the annotation editor extension would need to check if that curation toggle is on or off. 

Right, we can't use the page to attach that state because the backend cannot access it.

Maybe a good way would be to add a mechanism to the AnnotatorState to get/set custom flags - similar as Wicket component metadata. The sidebar could save the curation flag in the AnnotatorState and the annotation editor extension could pick it up from there.

**Comment by UWinch** [comment]
I don't think that this case is too different than the `DocumentOpenedEvent` that the `RecommendationService` listens to.

However, I can also see adding to the AnnotatorState as a possibility. I just did not want to make it bigger, because it's used a lot throughout the app. However, this solution might be more reusable, if we can make it general enough.

**Comment by UWinch** [comment]
Closing this because we went with a different solution (adding metadata to annotatorstate).

**Pull request closed without merging**
