### PR TITLE
#1212 - Offset for fireRender method of AnnotationEditorExtensionRegistry

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- add windowBeginOffset and windowEndOffset to editor extension classes

**How to test manually**

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this plesae?

**Comment by wpmp** [comment]
@reckart I made according changes in a PR in inception ( inception-project/inception#1058 ) so this can be reviewed and then merged.
Those two PRs will enable full rendering of recommendations in a PDF document in INCEpTION

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
