### PR TITLE
Allow annotation ui to be entered also via a (file)name parameter

### PR DESCRIPTION
**Pull request by jiemakel**
**What's in the PR**

This PR adds the option of accessing the annotation view of a document also via its (file)name in addition to its WebAnno document number.

For our use case, we require access to the annotation UI of a particular file via a stable URL. Previously, we maintained an external document name <-> WebAnno document number mapping, but this had to be updated every time we exported/imported the project (another requirement for us).

**How to test manually**

The parameter is n. So, to use the functionality, point your browser to `http://[webanno-server]/annotation.html?#!n=[document_name]&p=[project_number]` instead of `http://[webanno-server]/annotation.html?#!d=[document_number]&p=[project_number]`.

Note that the annotate/annotate-by-name versions of the routes don't work, but this is not due to changes I've made, instead they're broken in base as well (something to do with the editor component I think, which b0rks when parameters are not passed as fragment parameters but actual page parameters).

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@UWinch Could you have a look at this one?

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by UWinch** [comment]
Jenkins can you test this please?

**Comment by jcklie** [comment]
Jenkins, can you test this please?

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@jiemakel Could you check if the PR allows project maintainers to push to your branch? I think we are presently not allowed to do so - but we cannot merge unless the branch is up-to-date with the target branch (which it currently not is). If you could please allow us to push to your PR branch (there should be some checkbox for that in the PR), that would be great.

**Comment by jiemakel** [comment]
Didn't find the checkbox or anything else that would allow me to set permissions for that matter. The options mentioned in the GitHub help page for this just don't appear (although in the help page it is also mentioned that upstream maintainer access to pull request branches should be enabled by default). 

Anyway, found a button to update the branch to master instead, and duly pressed it :D.

**Comment by reckart** [comment]
Thanks!

**Comment by reckart** [comment]
@UWinch did you get a chance to review this?

**Pull request merged**
