### PR TITLE
#667 - Annotations starting within token A and ending within token B not supported

### PR DESCRIPTION
**Pull request by reckart**
Unit test and several fixes to the writer.

Fixing the reader seems to be more complicated.

### CODE REVIEW

**Comment by reckart** [comment]
@seyyaw There is a bug in the TSV3 reader and writer (#667). It seems to be a case that was not considered so far. I have set up unit tests and prepared a fix to the writer part.

The reader part seems more difficult. The code seems to expect that multi-token (sub)units always follow each other directly in the TSV. However, in the case that an annotation ends in the middle of a token, that is not the case:

```
#Text=This is a test .
1-1	0-4	This	*[1]	
1-2	5-7	is	_	
1-2.1	5-6	i	*[1]	
```

The reader code, thus, does not detect that 1-2.1 is still part of 1-1 and creates two annotations instead when reading this file.

**Comment by seyyaw** [comment]
@reckart Ok: I will check it

**Comment by reckart** [comment]
@seyyaw if you want to make any code changes related to this, please commit them to the `issue667-tsv3multisubtoken` branch, not to master or 3.3.x.

**Comment by seyyaw** [comment]
Ok good

**Comment by reckart** [comment]
@seyyaw I have added additional unit tests for complex combinations of tokens, subtokens and zero-witdh tokens. It seems that there are still some issues even in writing the data. E.g. in one case, a subtoken that was in the CAS does not appear at all in the TSV3 output. However, most problems appear to be in the reading of the data. It seems that reading of sub-token annotation is really only supported in a few very simple cases. 

So we have various failing tests now, some with preliminary reference data, some without any reference data yet. But the tests can be used for debugging / fixing.

**Comment by reckart** [comment]
This works with the new reader/writer from #676. No need anymore for this PR.

**Pull request closed without merging**
