### PR TITLE
#316 - Text selection behavior while dragging mouse

### PR DESCRIPTION
**Pull request by reckart**
- Create selectable stretching spacer element between chunks
- Adjust annotation creation code to handle spacer elements

### CODE REVIEW

**Comment by kazukisan** [comment]
Thanks for the PR on this. But on Mac OSX, I somehow still experience the same behavior with regard to jittery highlighting behevior on both Chrome  (ver 62) and Safari (ver 10.1.2).

What is your environment like to confirm the fix at least on some platforms? (I think I followed the correct way to do this, ```git branch``` shows feature/issue316-smooth-selection and locally, the application is from the fresh mvn clean installed.

**Comment by reckart** [comment]
The video below was recorded on OS X with Safari Version 11.0.1 (11604.3.5.1.1). When dragging within a single row the jitter is no longer there. Before, in particular the empty areas between the tokens would cause jitter.



However, there is still jitter when dragging across rows.



If you don't get the effect from the first video, maybe you have to clear your browser cache to ensure that you use the latest rendering code.

**Comment by kazukisan** [comment]
Thanks for the clarification!
I was testing for "across-row" highlighting, but the the screen recording makes it clear what improved. Thanks!

**Comment by reckart** [comment]
@kazukisan I had a look again at the screen recording for the changes you made to improve the selection process (https://www.youtube.com/watch?v=uLy8TaHbWE8), but I don't see very well cross-row effects. Can you tell if cross-row works better in your approach than in mine?

**Comment by kazukisan** [comment]
The approach I took for making cross-row effect good was to make the text highlighting work on character-level, It was only half-done in its implementation (not as optimized for performance), maybe something to look into again or from a different perspective. I just know that the code needs to be adjusted to work with the current WebAnno code.

**Pull request merged**
