### PR TITLE
Implementaion of jumping to slot filler

### PR DESCRIPTION
**Pull request by Jackwulujie**
We are responsible for issue #1353 Jump to slot filler.
At present, we can only complete the modification of the front end but the implementation of the function has not been completed yet.
We added a new button to the documentnavigator.html page to implement the new functionality and add it to the corresponding configuration file and java file. However, we encountered difficulties when actually coding the function in the documentnavigator.java file. actionShowSelectedDocument needs to use the SourceDocument parameter, but this parameter exists in the docListProvider, we tried a lot of methods but can't extract it.

### CODE REVIEW

**Comment by reckart** [comment]
Do you have any idea why there are so many changes in your PR?

**Comment by Jackwulujie** [comment]
We don't know why so many changes have been made. In fact, we only modify a few code, which is mainly concentrated in the lower part of the page. We speculate that this may be because some parts that are not fully displayed are fully expanded during upload, so the number of lines does not correspond to each other. Moreover, when we modify the codes or create new project on Inception, some files, such as license.txt at the top of the page, are automatically generated.  It's impossible for us to write or modify so many lines of code by ourselves.

**Comment by reckart** [comment]
@munterkalmsteiner Maybe you'd like to have a look at the git history of this branch to check what's wrong here?

**Comment by munterkalmsteiner** [comment]
@Jackwulujie please delete commit 58b5041 on your branch (locally and remotely, you can find howtos for that online). Then make sure your local feature branch is up-to-date with webanno master (again, you find tutorials for that online). 
I do not know why you have changes in the code you did not make yourself. Please drop me a mail if you encounter the problem again.

**Comment by Jackwulujie** [comment]
> @Jackwulujie please delete commit [58b5041](https://github.com/webanno/webanno/commit/58b50413c15d5af853b743338da8862a492adce3) on your branch (locally and remotely, you can find howtos for that online). Then make sure your local feature branch is up-to-date with webanno master (again, you find tutorials for that online).
> I do not know why you have changes in the code you did not make yourself. Please drop me a mail if you encounter the problem again.

I don't really know what you mean.

**Pull request closed without merging**
