### PR TITLE
#881 Use stable order in left side bar

### PR DESCRIPTION
**Pull request by Rentier**
- Use order for sorting if existing, else use display name

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by Rentier** [comment]
I looked into the source code of [OrderedComparator](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/OrderComparator.java). It does not check for the annotation `Order`. If you want that, then you would need to use [AnnotationAwareOrderComparator](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/annotation/AnnotationAwareOrderComparator.java).  I will fix it.

**Comment by reckart** [comment]
@Rentier good point - I guess I need to make changes in other places as well then ;) Thanks!

**Comment by Rentier** [comment]
I construct now my own comparator, as the types with Java 8 `thenComparing` do not work out.

**Comment by reckart** [comment]
@Rentier can you resolve conflicts please so I can merge?

**Pull request merged**
