### PR TITLE
#825 Add orthography layer into TCF reader

### PR DESCRIPTION
**Pull request by seyyaw**
Adding the TCF Orthography layer, with two features called correction and operation as webanno TCF reader and writer component

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@seyyaw thanks for the PR!

Could you please fix the dependencies?

```
[INFO] --- maven-dependency-plugin:3.0.2:analyze (default-cli) @ webanno-io-tcf ---
[WARNING] Used undeclared dependencies found:
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.transform-asl:jar:1.7.0:compile
[WARNING] Unused declared dependencies found:
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.castransformation-asl:jar:1.7.0:compile
```

It would be great if you could include a unit test which includes these new features.

**Comment by seyyaw** [comment]
I do not know why we have the warning regarding those dependencies. They are used actually.

**Comment by reckart** [comment]
@seyyaw you added a dependency on `de.tudarmstadt.ukp.dkpro.core.castransformation-asl` but instead the dependency should be on `de.tudarmstadt.ukp.dkpro.core.api.transform-asl` - this is also what Jenkins/Maven says.

**Comment by seyyaw** [comment]
@reckart got it, now the dependency is fixed.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@seyyaw I have had a look at the code. If I see it correctly, you have separated the code paths for forward and non-forward annotation which were previously both handled in `actionCreateOrUpdate`. This seems to have introduced some duplicate code. I need more time to better understand this.

**Comment by reckart** [comment]
Jenkins, could you please test this?

**Pull request merged**
