### PR TITLE
Fix #809 Unnecessary CPU load caused by autologout timer

### LINKED ISSUE #809: Webanno webpages eat CPU when idling
When a Webanno webpage is idling in an active browser tab, it causes constant CPU load, which it probably shouldn't. It looks like the autologout timer is called every second, updating the timer label causes cascading redraw.

### PR DESCRIPTION
**Pull request by Rentier**
Reducing the refresh rate reduces the load on my machine from constant 10% to 0% with spikes of 10.

### CODE REVIEW

**Comment by reckart** [comment]
If there are only 60 seconds remaining, then the display switches from minutes to seconds. With the present patch, the user will not see how many seconds are remaining in "real time" as the update happens only every 10 seconds. One option would be to reduce the update time when switching to display-seconds mode. Another option would be to fix the re-rendering problem in a different way, e.g. by somehow jailing the timer in a fixed-size area which does not trigger refreshes in other parts of the view, primarily in the brat view.

**Comment by Rentier** [comment]
Where is the code that switches from minutes to seconds? I would remove that feature for simplicity. Changing the tickrate means to reschedule the timer which is also more complicated. I do not know how to jail the timer, my CSS is not good enough and Google did not help.

**Comment by reckart** [comment]
Jenkins, test this please.

**Comment by reckart** [comment]
@Rentier Could you please verify whether the approach I have committed here also resolves the issue for you?

**Comment by Rentier** [comment]
@reckart The unnecessary CPU consumption and redraw is gone. Your fix is much better than mine.

**Pull request merged**
