### PR TITLE
#1791 - Cannot parse constraint rules with non-ASCII characters anymore

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Build constraint grammar parser with Unicode support
- Added unit tests for rules containing Unicode characters

**How to test manually**
* See issue description
* You can also import the file `webanno-constraints/src/test/resources/rules/unicode-characters.rules` included with this PR - lots of Unicode chars

**Automatic testing**
* [x] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Review by UWinch — COMMENTED** [review]
I tried adding cyrillic and the hindu example from your test file. However, I still have the same error. Does it work from the UI for you? Maybe my setup is faulty.

**Comment by reckart** [comment]
@UWinch did you try in WebAnno or in INCEpTION?

**Comment by UWinch** [comment]
> @UWinch did you try in WebAnno or in INCEpTION?

In INCEpTION.

**Comment by reckart** [comment]
@UWinch did you make sure that the INCEpTION you tried actually used a WebAnno version which included this PR?

**Comment by UWinch** [comment]
> @UWinch did you make sure that the INCEpTION you tried actually used a WebAnno version which included this PR?

Yes. Now also tried with webanno with the same result. @jcklie maybe you cold also try this?

**Comment by jcklie** [comment]
I tried both webanno and INCEpTION

2020-10-20 10:01:05 ERROR [admin] de.tudarmstadt.ukp.clarin.webanno.ui.core.page.ApplicationPageBase - admin: Error: Lexical error at line 6, column 45.  Encountered: "\u1205" (4613), after : "\"\u12ed"

Git branch says

`* bugfix/1791-Cannot-parse-constraint-rules-with-non-ASCII-characters-anymore`

**Review by UWinch — APPROVED** [review]
Works for me after manually deleting generated-sources of the parser. Tested adding unicode chars to existing rule file, as well as importing one with unicode. Tested with inception.

**Pull request merged**
