### PR TITLE
#1452 - Option to create annotation links without role label

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- Add option to enable/disable role labels for link features
- If role labels are disabled the UI label of the target span is shown instead

**How to test manually**
* Have two linked layers
* In the feature options for the link feature disable role labels
* See in the editor view that there is no possibility to enter a role label

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
@reckart I think this PR is ready for a review

**Comment by reckart** [comment]
Looks quite ok. I like the idea of showing the label of the target annotation instead of the role label when the role label cannot be set. 

When the option to set the role label is turned off, the choice for the tagset should not show up since it doesn't really make any sense then.

Could you include documentation for the new feature please?

I exported and re-imported a file annotated without role labels as TSV3 and it worked fine :)

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
To avoid unexpected behavior, the tagset setting should probably also be cleared if the role feature is disabled.

**Comment by wpmp** [comment]
Done :)

I added some documentation in the `Creating annotations` topic for `Link Features`.
I guess we should also add some documentation regarding the creation of link features and the new options, however I think at first we need to restructure the [https://inception-project.github.io//releases/0.11.2/docs/user-guide.html#sect_projects_layers_features](section).
Or should I add it elsewhere?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
This PR is ready for another review

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@wpmp could you have a look at this conflict?

**Comment by wpmp** [comment]
@reckart done

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
