### PR TITLE
#1441 - Make set and delete buttons for LinkFeatures usable outside the annotation sidebar

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- add event for deleting a slot in the LinkFeatureEditor

**How to test manually**
* Annotate with link features and fill / edit / delete slots

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
@reckart is this roughly what you meant in #1411 ?

**Comment by wpmp** [comment]
So, which `stop()` method do you mean?
From `IEvent`?
I haven't implemented this IF in `LinkFeatureDeletedEvent` and if I would do so I'd have to implement the `stop` method among others myself.
I'm not quiet sure what I'd had to implement there.
Or is there an implementation of `IEvent` which I could extend and have not seen yet?

**Comment by reckart** [comment]
The `OnEvent` annotation has a flag `stop` which has the same purpose. So: `OnEvent(stop=true)` should do the trick.

**Comment by wpmp** [comment]
Ah, ok, thanks!

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
What happened there?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
