### PR TITLE
#1411 - Delete button for LinkFeatureEditor missing

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- fix visibility setting for delete button in LinkFeatureEditor

**How to test manually**
1. Open a document that has a layer with a link feature
2. Select an annotation that has a link
3. Select the filled slot
4. Delete button is there
5. Click it to test functionality

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
@reckart Do not merge yet, the button appears but it is not working

**Comment by reckart** [comment]
The button works on the right side. I'd suggest to handle making it work on the left side as well separately. IMHO it will need to involve replacing the current "auto commit" code that is at the end of the del action handler with some `onDelete(AjaxTarget...)`  method and then to implement that method differently in left/right-side instantiations of the feature editor.

**Comment by wpmp** [comment]
That's true, ok I'll have a look

**Pull request merged**
