### PR TITLE
#1764 - Error when annotating new layer for the first time

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Replace the Spring ConcurrentReferenceHashMap with a simpler synchronized WeakHashMap turned into a set because the Spring class seems to "loose" entries without any good reason
- Added a test case for the type-system-changed event
- Added some trace-level logging code for debugging

**How to test manually**
* See issue description

**Automatic testing**
* [x] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@UWinch looks like the problem was that `ConcurrentReferenceHashMap` uses weak references for the *keys and values* while the code (or rather me writing the code) expected only the *keys* to be weak references as in a normal `WeakHashMap`. So when we applied `newSetFromMap()` to the `ConcurrentReferenceHashMap`, we internally created a `Map<CasHolder, Boolean>` in which the `CasHolder` keys would disappear when the `Boolean` dummy value was garbage collected (weak value references). I switch the a `synchronized(newSetFromMap(WeakHashMap))` where only the keys are weak, so the `CasHolder` should now only disappear from the set when it has been garbage collected - which was the original expectation and intended behaviour when the code was conceptualised.

**Comment by UWinch** [comment]
I'm still getting the error when:

- open a document first
- add a new layer via settings
- try to annotate with the new layer on the same document

Does it work for you?

**Comment by reckart** [comment]
When I tested, I am pretty sure it worked for me. Maybe try cleaning/rebuilding the workspace?

**Comment by reckart** [comment]
@UWinch you were right, it was still broken in INCEpTION. The issue appears to have been that immediately after adding the layer, the CASes were re-loaded into memory by the indexing thread using NO_UPGRADE. And afterwards, when we opened a document in the annotation editor, the FORCE_UPGRADE flag was ignored because the CAS was already in memory. I have changed the code to upgrade/repair CASes even if they were borrowed from the pool. That seems to fix the loophole.

**Review by UWinch — APPROVED** [review]
Thanks a lot for the fix.

**Pull request merged**
