### PR TITLE
#842 - Extend forward annotation to a feature without a tagset

### PR DESCRIPTION
**Pull request by seyyaw**
Extend forward annotation to free-text annotation feature when
1) it is locked-to-token annotation layer
2) There is only one annotation feature which is enabled and visible at a time. If there multiple features, they should be invisibile and disable to allow forward annotation for free-text annotation
How it works
1) enable forward annotation (using the checkbox)
2) type the annotation in the text-field and pres the ENTER KEY
If nothing is typed in the text-field, annotation will be delted and focus will move to the next token

### CODE REVIEW

**Comment by seyyaw** [comment]
Thanks @reckart . How do you change the base branch ?

**Comment by reckart** [comment]
You can change the base by pressing on "edit" next to the title. It is a bit hidden ;)

I'll try to review the PR over the weekend.

**Comment by reckart** [comment]
@seyyaw I have had a look at the code. If I see it correctly, you have separated the code paths for forward and non-forward annotation which were previously both handled in `actionCreateOrUpdate`. This seems to have introduced some duplicate code. I need more time to better understand this.

**Comment by reckart** [comment]
Jenkins, could you please test this?

**Comment by seyyaw** [comment]
@reckart I thought it is better to separate the logic even if there is large amount of code overlaps. The other option is to add more parameters to the method but then we should change method calls in several places. Let me know your thought on this.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
